
# Challenge 2: Working with Data
- *Assigned: August 13, 2019*
- *Due: at 6pm on August 20, 2019*

# Assignment
You should have received an email invitation to access this assigment in Github Classroom.  If you haven't received it, please [post an Issue](https://github.com/ibiem-master/community)

The goal of this challenge is to help you get more familiar with the material covered in the following lessons from [SWC: R for Reproducible Scientific Analysis](http://swcarpentry.github.io/r-novice-gapminder/)

- [Seeking Help](http://swcarpentry.github.io/r-novice-gapminder/03-seeking-help/)
- [Data Structures](http://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/)
- [Exploring Data Frames](http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/)
- [Subsetting Data](http://swcarpentry.github.io/r-novice-gapminder/06-data-subsetting/)

You will need to:

1. Initialize a new project in RStudio based on this repository (you might want to review the [relevant instructions from Challenge 1](https://github.com/ibiem-master/challenge_1/blob/master/README.md#initialize-a-new-project))

2. Fill the blank R code chunks in [challenge2_assignment.Rmd](challenge2_assignment.Rmd)

3. Modify the header of [challenge2_assignment.Rmd](challenge2_assignment.Rmd) (you might want to review the [relevant instructions from Challenge 1](https://github.com/ibiem-master/challenge_1/blob/master/README.md#modify-the-header)

4. Submit the Assignment (you might want to review the [relevant instructions from Challenge 1](https://github.com/ibiem-master/challenge_1/blob/master/README.md#submitting-the-assignment) ).  You should submit the following:
  - `challenge2_assignment.Rmd` : your modified version of the R Notebook that you received in your repo
  - `challenge2_assignment.html` : the output from knitting your revised `challenge2_assignment.Rmd`

5. Optional (but *strongly* recommended): frequently commit changes and push to GitHub.


## Expectations
You should focus on the following when working on this assignment:
  1. Correct Result - do the results seem reasonable?
  2. Code Quality - is your code well written?
  3. Git Commit Quality - have you made frequent commits? Are your commit messages informative?
  4. SessionInfo - did you include a sessionInfo() call?


### Git Commit Message Quality
  - For some helpful hints [search the internet for "writing good commit messages"](https://duckduckgo.com/?q=writing+good+commit+messages)
  - You may also want [examples of what not to do](https://xkcd.com/1296/)

### SessionInfo
Including a `SessionInfo` statement at the end of your R Notebook is good reproducibility practice.  This time it is included already in `challenge2_assignment.Rmd`; next time you might not be so lucky! 

